# This file was generated by GoReleaser. DO NOT EDIT.
cask "zgx" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "ed614a05fbb62fdf2e43ce030284d7e62597a0d93d9daaa58e927276f7755d1e"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c76b9b9f5ec562f09141bf4d7fdd16e5cb24f21741090a7f48c9106f2db55aba"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c3a4866f2effdff0a630cbeab1ec2fa8555bf933ab3f96b572a6c83c9d95a651"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "30511377541a906cc3f5dee67212d0f291ee18ea20c5f35b84b23eff5e48a84c"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zgx"
  desc "Portable CLI to configure HP ZGX nano over SSH"
  homepage "https://github.com/AndersSol/zgx-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zgx"

  # No zap stanza required

end
