# This file was generated by GoReleaser. DO NOT EDIT.
cask "zgx" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "193b55b94345780bf0d85a1df745ffadeef7c6d02cad73dc3e264703376f8017"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e7ed29c1710fcb7d9087ad3d56d6824b154cc8f5ae1b0efe04a36d060530883"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c7abe112ebfbf607b4bbe0cacc7146cc5f1699606aea19962d1b1c4b21e24b27"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "91dcff7cd4b232576d01144e20517ea708c30c722224edbf1c5f8a8a4036f4a5"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zgx"
  desc "Portable CLI to configure HP ZGX nano over SSH"
  homepage "https://github.com/AndersSol/zgx-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zgx"

  # No zap stanza required

end
