# This file was generated by GoReleaser. DO NOT EDIT.
cask "zgx" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "ac00cc638318485859e7bac24402ac435ee9f31972e61bb147976efc1b19268f"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "443fe3f970bf859911a505d80dfb8a90b8affcd4326c5e66d38be767dab2b753"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d17b0af9521a5425630168ab4611fb8a427e1c1ff7687c8418f4e916dbebc102"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "72598dc7154b3f692ef1fc394d2764c93e8bb820e71c15ce296255c8cf57c76f"
      url "https://github.com/AndersSol/zgx-cli/releases/download/v#{version}/zgx-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zgx"
  desc "Portable CLI to configure HP ZGX nano over SSH"
  homepage "https://github.com/AndersSol/zgx-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zgx"

  # No zap stanza required

end
